version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'master'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '08:00'
      timezone: 'Europe/Paris'
    reviewers:
      - 'benard-g'
    labels:
      - 'dependency'
